# Generated by Django 4.1.7 on 2023-04-15 08:04

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', accounts.managers.AccountManager()),
            ],
        ),
    ]
