# Generated by Django 4.1.7 on 2023-04-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('applicants', 'Соискатель'), ('employers', 'Работодатель')], default='applicants', max_length=250, verbose_name='Тип пользователя'),
        ),
    ]
