# Generated by Django 4.1.7 on 2023-04-14 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='Полное имя')),
                ('position', models.CharField(max_length=128, verbose_name='Должность')),
                ('salary', models.PositiveIntegerField(max_length=8, verbose_name='Желаемая зарплата')),
                ('about', models.TextField(max_length=2000, verbose_name='О себе')),
                ('telegram', models.CharField(max_length=256, verbose_name='Nickname telegram')),
                ('facebook', models.CharField(max_length=512, null=True, verbose_name='Facebook profile URL')),
                ('linkedin', models.CharField(max_length=512, null=True, verbose_name='Linkedin profile URL')),
                ('is_published', models.BooleanField(default=True, verbose_name='Статус публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
        ),
    ]
