# Generated by Django 4.1.7 on 2023-04-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_alter_resume_options_alter_resume_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='facebook',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Facebook profile URL'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='linkedin',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Linkedin profile URL'),
        ),
    ]
