# Generated by Django 4.1.6 on 2023-04-19 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название вакансий')),
                ('category', models.CharField(choices=[('information technology', 'Информационные технологий'), ('pharmacy', 'Фармацевтика'), ('construction', 'Строительство'), ('cybersport', 'Киберспорт'), ('restaurant business', 'Ресторанный бизнес'), ('energy', 'Энергетика')], max_length=256, verbose_name='Сфера')),
                ('salary_start', models.PositiveIntegerField(verbose_name='Минимальная зароботная плата')),
                ('salary_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальная зароботная плата')),
                ('about', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Описание')),
                ('requirements', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Требования')),
                ('is_published', models.BooleanField(default=True, verbose_name='Статус публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram', models.CharField(max_length=256, verbose_name='Nickname telegram')),
                ('facebook', models.CharField(blank=True, max_length=512, null=True, verbose_name='Facebook profile URL')),
                ('linkedin', models.CharField(blank=True, max_length=512, null=True, verbose_name='Linkedin profile URL')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансий',
            },
        ),
    ]
