# Generated by Django 4.1.6 on 2023-04-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
